const $=s=>document.querySelector(s),app=$('#app');
let tok=localStorage.t,usr=JSON.parse(localStorage.u||'null'),charts={};
const esc=s=>String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const $$=n=>'$'+(+n).toFixed(n>0&&n<.01?6:4);
async function api(p,m='GET',b,f){const h={};if(tok)h.Authorization='Bearer '+tok;if(b&&!f)h['Content-Type']='application/json';
 const r=await fetch('/api/'+p,{method:m,headers:h,body:f?b:b&&JSON.stringify(b)});const j=await r.json().catch(()=>({}));
 if(r.status==401&&tok){logout();throw Error('Session expired')}if(!r.ok)throw Error(j.detail||'Error');return j}
function toast(m){const t=$('#toast');t.textContent=m;t.classList.remove('hidden');setTimeout(()=>t.classList.add('hidden'),3000)}
function logout(){localStorage.clear();tok=usr=null;location.hash='#/'}
const P=['dashboard','chat','docs','analytics','cache','settings','about'];
function nav(){$('#nav').innerHTML=`<a href="#/" class="font-bold grad text-lg mr-3">◈ SmartRAG</a>`+(tok?P.map(p=>`<a class="btn2 text-sm capitalize" href="#/${p}">${p=='docs'?'Documents':p=='cache'?'Cache Monitor':p}</a>`).join('')+`<span class="ml-auto text-sm opacity-70">${esc(usr.name)}</span><button class="btn2 text-sm" onclick="logout()">Logout</button>`:`<a class="btn2 text-sm" href="#/about">About</a><a class="btn ml-auto text-sm" href="#/auth">Login / Register</a>`)}
function ch(id,type,labels,sets){charts[id]?.destroy();const d=type=='doughnut';charts[id]=new Chart($('#'+id),{type,data:{labels,datasets:sets},options:{responsive:true,maintainAspectRatio:false,tension:.4,plugins:{legend:{labels:{boxWidth:10}}},scales:d?{}:{x:{grid:{color:'#ffffff10'}},y:{grid:{color:'#ffffff10'},beginAtZero:true}}}})}
const col=['#22d3ee','#a78bfa','#f472b6','#fbbf24','#34d399'];
const card=(t,v,s='')=>`<div class="g p-4 fade"><div class="text-xs opacity-60">${t}</div><div class="text-2xl font-bold grad">${v}</div><div class="text-xs opacity-50">${s}</div></div>`;
const cv=(id,t)=>`<div class="g p-4 fade"><div class="text-sm mb-2 opacity-70">${t}</div><div class="cv"><canvas id="${id}"></canvas></div></div>`;
const pages={
async ''(){app.innerHTML=`<section class="text-center py-20 fade"><h1 class="text-5xl md:text-7xl font-extrabold grad">SmartRAG</h1><p class="mt-4 text-xl opacity-80">Cost-aware RAG assistant with semantic caching &amp; smart model routing</p><a href="#/${tok?'dashboard':'auth'}" class="btn inline-block mt-8">Get started →</a></section><div class="grid md:grid-cols-3 gap-4">${[['📄 Cited answers','Upload PDFs, ask questions, get answers with source citations.'],['⚡ Semantic cache','Similar questions reuse past answers – zero LLM cost, instant latency.'],['🧭 Cost routing','Simple queries use a cheap model; complex ones use a powerful model.'],['📊 Live analytics','Tokens, latency, cache hit rate and dollars saved – from real logs.'],['🗄 Vector search','Chunk embeddings stored in SQLite with cosine retrieval.'],['🔧 Configurable','Any OpenAI-compatible LLM/embedding API via .env.']].map(a=>`<div class="g p-5 fade"><b>${a[0]}</b><p class="text-sm opacity-70 mt-1">${a[1]}</p></div>`).join('')}</div>`},
async auth(){let reg=false;const draw=()=>{app.innerHTML=`<form id="af" class="g p-6 max-w-sm mx-auto mt-10 space-y-3 fade"><h2 class="text-2xl font-bold grad">${reg?'Register':'Login'}</h2>${reg?'<input class="inp" name="name" placeholder="Name">':''}<input class="inp" name="email" type="email" placeholder="Email" required><input class="inp" name="password" type="password" placeholder="Password (6+)" required><button class="btn w-full">${reg?'Create account':'Login'}</button><a href="#" id="sw" class="text-sm opacity-70 block text-center">${reg?'Have an account? Login':'New here? Register'}</a></form>`;
 $('#sw').onclick=e=>{e.preventDefault();reg=!reg;draw()};$('#af').onsubmit=async e=>{e.preventDefault();try{const r=await api(reg?'register':'login','POST',Object.fromEntries(new FormData(e.target)));tok=localStorage.t=r.token;usr=r.user;localStorage.u=JSON.stringify(usr);location.hash='#/dashboard'}catch(x){toast(x.message)}}};draw()},
async dashboard(){const s=await api('stats'),t=s.totals,hr=t.n?(100*t.hits/t.n).toFixed(1):0;
 app.innerHTML=`<div class="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-3">${card('Queries',t.n)}${card('Cache hit rate',hr+'%',t.hits+' hits')}${card('Cost saved',$$(t.cache_saved+t.routing_saved),'cache + routing')}${card('Avg latency',t.lat.toFixed(0)+' ms')}${card('Documents',t.docs,t.chunks+' chunks')}${card('Total cost',$$(t.cost))}</div><div class="grid md:grid-cols-2 gap-4 mt-4">${cv('c1','Queries per day (total vs cache hits)')}${cv('c2','Model usage')}${cv('c3','Latency – last 30 queries (ms)')}${cv('c4','Cost vs saved per day ($)')}</div>`;
 const dl=s.daily.map(d=>d.d);ch('c1','bar',dl,[{label:'Queries',data:s.daily.map(d=>d.q),backgroundColor:col[0]},{label:'Hits',data:s.daily.map(d=>d.hits),backgroundColor:col[1]}]);
 ch('c2','doughnut',s.models.map(m=>m.model),[{data:s.models.map(m=>m.n),backgroundColor:col}]);
 ch('c3','line',s.lat.map((l,i)=>i+1),[{label:'ms',data:s.lat.map(l=>l.latency),borderColor:col[0],pointBackgroundColor:s.lat.map(l=>l.cache_hit?col[4]:col[3])}]);
 ch('c4','line',dl,[{label:'Spent',data:s.daily.map(d=>d.cost),borderColor:col[2]},{label:'Saved (cache)',data:s.daily.map(d=>d.saved),borderColor:col[4]}])},
async chat(){const h=await api('history');app.innerHTML=`<div class="g p-4 flex flex-col" style="height:78vh"><div id="msgs" class="flex-1 overflow-y-auto space-y-3 pr-1"></div><form id="cf" class="flex gap-2 mt-3"><input id="q" class="inp" placeholder="Ask about your documents…" autocomplete="off"><button class="btn">Send</button><button type="button" id="clr" class="btn2">Clear</button></form></div>`;
 const M=$('#msgs'),add=(h,me)=>{const d=document.createElement('div');d.className='fade max-w-[85%] p-3 rounded-2xl text-sm '+(me?'ml-auto bg-cyan-500/20':'bg-white/5');d.innerHTML=h;M.appendChild(d);M.scrollTop=M.scrollHeight;return d};
 const ans=(r)=>`<div class="whitespace-pre-wrap">${esc(r.answer)}</div><div class="flex flex-wrap gap-1 mt-2"><span class="tag ${r.cache_hit?'hit':'miss'}">${r.cache_hit?'CACHE HIT '+(r.similarity??r.sim)?.toString().slice(0,5):'CACHE MISS'}</span><span class="tag">${esc(r.model)}</span><span class="tag">${r.latency.toFixed?r.latency.toFixed(0):r.latency} ms</span><span class="tag">${r.tin}→${r.tout} tok</span><span class="tag">${$$(r.cost)}${r.saved?' · saved '+$$(r.saved):''}</span></div><details class="mt-2"><summary class="cursor-pointer opacity-70">Sources (${r.sources.length})</summary>${r.sources.map(s=>`<div class="mt-1 p-2 bg-black/30 rounded text-xs"><b>[${s.n}] ${esc(s.doc)}</b> · chunk ${s.idx} · score ${s.score}<br>${esc(s.text)}…</div>`).join('')}</details>`;
 h.forEach(r=>{add(esc(r.query),1);add(ans({...r,similarity:r.sim}))});
 $('#clr').onclick=async()=>{if(confirm('Clear chat history?')){await api('history','DELETE');pages.chat()}};
 $('#cf').onsubmit=async e=>{e.preventDefault();const q=$('#q').value.trim();if(!q)return;$('#q').value='';add(esc(q),1);const w=add('<span class="opacity-60">Thinking…</span>');try{const r=await api('chat','POST',{query:q});w.innerHTML=ans(r)}catch(x){w.innerHTML='⚠ '+esc(x.message)}}},
async docs(){const d=await api('docs');app.innerHTML=`<div class="g p-6 fade"><h2 class="text-xl font-bold grad mb-3">Documents</h2><label class="block border-2 border-dashed border-white/20 rounded-xl p-8 text-center cursor-pointer hover:border-cyan-400" id="dz">Drop or click to upload PDF / TXT / MD / CSV<input id="fi" type="file" multiple accept=".pdf,.txt,.md,.csv" class="hidden"></label><table class="mt-4"><tr><th>Name<th>Chars<th>Chunks<th>Added<th></tr>${d.map(x=>`<tr><td>${esc(x.name)}<td>${x.chars}<td>${x.nchunks}<td>${x.created}<td><button class="btn2" onclick="delDoc(${x.id})">Delete</button></tr>`).join('')||'<tr><td colspan=5 class="opacity-60">No documents yet</tr>'}</table></div>`;
 const up=async fs=>{for(const f of fs){const fd=new FormData();fd.append('file',f);toast('Indexing '+f.name+'…');try{await api('docs','POST',fd,1)}catch(x){toast(f.name+': '+x.message)}}pages.docs()};
 $('#fi').onchange=e=>up(e.target.files);$('#dz').ondragover=e=>e.preventDefault();$('#dz').ondrop=e=>{e.preventDefault();up(e.dataTransfer.files)}},
async analytics(){const s=await api('stats'),t=s.totals;const tot=t.cost+t.cache_saved+t.routing_saved;
 app.innerHTML=`<div class="grid grid-cols-2 md:grid-cols-4 gap-3">${card('Tokens in',t.tin)}${card('Tokens out',t.tout)}${card('Saved by cache',$$(t.cache_saved))}${card('Saved by routing',$$(t.routing_saved))}</div><div class="grid md:grid-cols-2 gap-4 mt-4">${cv('a1','Tokens by model')}${cv('a2','Savings breakdown ($)')}${cv('a3','Cost by model ($)')}<div class="g p-4"><div class="text-sm opacity-70 mb-2">Without SmartRAG (all strong model, no cache): ${$$(tot)}</div><div class="text-sm">Actual spend: ${$$(t.cost)} → <b class="grad">${tot?(100*(1-t.cost/tot)).toFixed(1):0}% saved</b></div></div></div>`;
 const m=s.models.map(x=>x.model);ch('a1','bar',m,[{label:'In',data:s.models.map(x=>x.tin),backgroundColor:col[0]},{label:'Out',data:s.models.map(x=>x.tout),backgroundColor:col[1]}]);
 ch('a2','doughnut',['Cache','Routing','Spent'],[{data:[t.cache_saved,t.routing_saved,t.cost],backgroundColor:[col[4],col[0],col[2]]}]);ch('a3','bar',m,[{label:'Cost',data:s.models.map(x=>x.cost),backgroundColor:col[3]}])},
async cache(){const c=await api('cache'),s=(await api('stats')).totals;app.innerHTML=`<div class="grid grid-cols-3 gap-3 mb-4">${card('Entries',c.length)}${card('Hits',s.hits)}${card('Misses',s.n-s.hits)}</div><div class="g p-6 fade"><div class="flex justify-between mb-3"><h2 class="text-xl font-bold grad">Semantic Cache</h2><button class="btn2" onclick="clrCache()">Clear all</button></div><div class="overflow-x-auto"><table><tr><th>Query<th>Model<th>Cost<th>Hits<th>Created<th></tr>${c.map(x=>`<tr><td>${esc(x.query)}<td>${esc(x.model)}<td>${$$(x.cost)}<td>${x.hits}<td>${x.created}<td><button class="btn2" onclick="delC(${x.id})">✕</button></tr>`).join('')||'<tr><td colspan=6 class="opacity-60">Cache is empty</tr>'}</table></div></div>`},
async settings(){const s=await api('settings');app.innerHTML=`<div class="g p-6 max-w-xl mx-auto space-y-4 fade"><h2 class="text-xl font-bold grad">Settings</h2><p class="text-sm opacity-70">LLM: ${s.llm_configured?'API configured':'offline extractive mode (set LLM_API_KEY in .env)'} · Embeddings: ${s.embed_configured?'API':'local hashing'}<br>Cheap: ${esc(s.cheap_model)} · Strong: ${esc(s.strong_model)}</p>${[['cache_threshold','Cache similarity threshold',.5,1,.01],['route_threshold','Routing threshold (higher = more cheap)',0,1,.05],['top_k','Retrieved chunks (top-k)',1,10,1]].map(f=>`<label class="block text-sm">${f[1]}: <b id="v_${f[0]}">${s[f[0]]}</b><input type="range" id="${f[0]}" min="${f[2]}" max="${f[3]}" step="${f[4]}" value="${s[f[0]]}" class="w-full" oninput="$('#v_${f[0]}').textContent=this.value"></label>`).join('')}<button class="btn" id="sv">Save</button></div>`;
 $('#sv').onclick=async()=>{await api('settings','PUT',{cache_threshold:$('#cache_threshold').value,route_threshold:$('#route_threshold').value,top_k:$('#top_k').value});toast('Saved')}},
async about(){app.innerHTML=`<div class="g p-6 max-w-2xl mx-auto fade space-y-3"><h2 class="text-2xl font-bold grad">About SmartRAG</h2><p>SmartRAG reduces LLM spend with two levers: a <b>semantic cache</b> (embedding similarity) and a <b>complexity router</b> that sends easy questions to a cheap model.</p><p class="opacity-80 text-sm">Stack: FastAPI · SQLite · NumPy vector search · pypdf · Three.js · Chart.js · Tailwind. Any OpenAI-compatible LLM/embedding API works.</p></div>`}};
window.delDoc=async i=>{await api('docs/'+i,'DELETE');pages.docs()};window.delC=async i=>{await api('cache/'+i,'DELETE');pages.cache()};window.clrCache=async()=>{await api('cache','DELETE');toast('Cache cleared');pages.cache()};
async function route(){const p=location.hash.slice(2);if(P.includes(p)&&p!='about'&&!tok)return location.hash='#/auth';nav();Object.values(charts).forEach(c=>c.destroy());charts={};try{await(pages[p]||pages[''])()}catch(e){toast(e.message)}}
Chart.defaults.color='#9fb0d0';addEventListener('hashchange',route);route();
// 3D background
(()=>{const cvs=$('#bg'),r=new THREE.WebGLRenderer({canvas:cvs,alpha:true,antialias:true}),sc=new THREE.Scene(),cam=new THREE.PerspectiveCamera(60,1,.1,100);cam.position.z=7;
 const ico=new THREE.Mesh(new THREE.IcosahedronGeometry(2.2,1),new THREE.MeshBasicMaterial({color:0x22d3ee,wireframe:true,transparent:true,opacity:.35}));sc.add(ico);
 const n=900,p=new Float32Array(n*3);for(let i=0;i<n*3;i++)p[i]=(Math.random()-.5)*20;const pg=new THREE.BufferGeometry();pg.setAttribute('position',new THREE.BufferAttribute(p,3));
 const pts=new THREE.Points(pg,new THREE.PointsMaterial({color:0xa78bfa,size:.04}));sc.add(pts);let mx=0,my=0;
 addEventListener('mousemove',e=>{mx=e.clientX/innerWidth-.5;my=e.clientY/innerHeight-.5});
 const rs=()=>{r.setSize(innerWidth,innerHeight);cam.aspect=innerWidth/innerHeight;cam.updateProjectionMatrix()};rs();addEventListener('resize',rs);
 (function a(){ico.rotation.x+=.002;ico.rotation.y+=.003;pts.rotation.y+=.0006;cam.position.x+=(mx*2-cam.position.x)*.03;cam.position.y+=(-my*2-cam.position.y)*.03;cam.lookAt(0,0,0);r.render(sc,cam);requestAnimationFrame(a)})()})();
